### ISSUE TITLE
sdk install

### ISSUE THREAD

**Issue by icefiresong24** [ChaosGroup/vray_gltf#2]
Hello, after installing the SDK, I started the examples program and encountered the following problems
![image](https://user-images.githubusercontent.com/67216778/220287365-716b5b6a-c044-4d93-bad1-5ec10f028260.png)
How can I fix it?

**Comment by vkoylazov** [comment]
Hello, when installing the V-Ray AppSDK, it modifies the V-Ray license settings to point to localhost; if your V-Ray license is set up on another remote machine, use the setvrlservice tool to return the license settings to the original ones; see here for more information: https://docs.chaos.com/display/APPSDK/Changing+your+License+Settings

**Comment by vkoylazov** [comment]
Ok, great!
